@startuml User course sequence

header USER VIEW COURSES (LIST + DETAIL) SEQUENCE
actor User
control server
database course

opt READ: User view available course list
  User -> server: GET /v1/courses
  activate server
  server -> course: find all courses (active, published)
  activate course
  alt <font color=red>error</font>
    course --> server: error
    server --> User: 500, internal error
  else <font color=green>success</font>
    course --> server: list of courses
    server --> User: 200, course list
  end
  deactivate course
  deactivate server
end

opt READ: User view course detail
  User -> server: GET /v1/courses/:courseId
  activate server
  server -> course: find course by ID
  activate course
  alt <font color=red>not found</font>
    course --> server: null
    server --> User: 404, course not found
  else <font color=green>success</font>
    course --> server: course detail
    server --> User: 200, course detail
  end
  deactivate course
  deactivate server
end

@enduml
