@startuml Admin get courses list
  header ADMIN GET COURSE LIST
  start
    :find all courses in database with isActive = true && isArchived = false;
    if (have error?) then (yes)
      :response 500, internal error;
      stop
    else (no)
      :response 200, courses list;
    endif
  end
@enduml