@startuml Topic admin sequence

header CREATE TOPIC ADMIN SEQUENCE
actor Admin 
control server
database topic
database course

opt CREATE: Admin create topic
  Admin -> server: POST /v1/topics/create-topic
  activate server
  server -> server: check token
  alt <font color=red>token invalid</font>
    server --> Admin: 401, unauthorized error
  else <font color=green>token valid</font>
    server -> server: check isAdmin
    alt <font color=red>is not admin</font>
      server --> Admin: 403, forbidden error
    else <font color=green>is admin</font>
      server -> course: check course exists
      activate course
      alt <font color=red>course not found</font>
        course --> server: null
        server --> Admin: 404, course not found
      else <font color=green>valid course</font>
        course --> server: course data
        deactivate course
        server -> topic: create topic (title, category, description, courseId)
        activate topic
        alt <font color=red>insert failed</font>
          topic --> server: error
          server --> Admin: 500, internal error
        else <font color=green>success</font>
          topic --> server: topic id
          server --> Admin: 200, topic created
        end
        deactivate topic
      end
    end
    deactivate server
  end
end

@enduml
