@startuml Admin delete topic
header ADMIN DELETE TOPIC
start
  :check token and isAdmin;
  if (unauthorized?) then (yes)
    :response 401 or 403 error;
    stop
  else (authorized)
    :find topic by topicId;
    if (not found?) then (yes)
      :response 404, topic not found;
      stop
    else (found)
      :delete topic;
      if (delete failed?) then (yes)
        :response 500, internal error;
      else (success)
        :response 200, topic deleted;
      endif
    endif
  endif
end
@enduml
